- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create a App directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading Zip file Extracting App content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest:  /app
    remote_src: yes