- name: Setup MongoDB
  hosts: all
  become: yes
  tasks:
    - name: Copy MongoDB repo File
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install the MongoDB server
      ansible.builtin.yum:
        name: mongodb-org
        state: latest
    - name: Update listen address from 127.0.0.1 to 0.0.0.0
      ansible.builtin.replace:
          path: /etc/mongod.conf
          regexp: '127.0.0.1'
          replace: '0.0.0.0'
    - name: Enable MongoDB service
      ansible.builtin.systemd:
        name: mongod
        enabled: yes

    - name: Restart MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: restarted













  # systemctl enable mongod &>>/tmp/roboshop.log
  # systemctl restart mongod &>>/tmp/roboshop.log
  # stat_check $?


  # here we want Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  # echo -e "\e[34mUpdate listen address \e[0m"
  # sed -i -e 's//etc/mongod.conf/' /etc/mongod.conf &>>/tmp/roboshop.log
  # stat_check $?

  #echo -e "\e[35mStart  MongoDB server \e[0m"
  #systemctl daemon-reload
  #systemctl restart mongod &>>/tmp/roboshop.log
  #stat_check $?